<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checkup Detail</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        .container {
            width: 80%;
            margin: 20px auto;
            background-color: #ffffff;
            padding: 20px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        h2 {
            text-align: center;
            color: #2C3E50;
            margin-bottom: 20px;
        }

        .checkup-details {
            margin-top: 20px;
            font-size: 14px;
            color: #34495E;
        }

        .checkup-details p {
            margin: 10px 0;
            line-height: 1.6;
        }

        .checkup-details strong {
            color: #16A085;
        }

        .checkup-details p {
            background-color: #ecf0f1;
            border-radius: 5px;
            padding: 10px;
            margin: 10px 0;
        }

        .checkup-details p:nth-child(odd) {
            background-color: #f5f5f5;
        }

        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 12px;
            color: #7F8C8D;
        }

        .footer p {
            margin: 0;
        }
    </style>
</head>
<body>
<div class="container">
        <h2>Checkup Details</h2>

        <!-- Tampilkan data pemeriksaan (Checkup) di sini -->
        <div class="checkup-details">
            <p><strong>ID Periksa:</strong> {{ $checkup->id }}</p>
            <p><strong>Nama Pasien:</strong> {{ $checkup->enlistment->patient_name ?? 'N/A' }}</p>
            <p><strong>Tanggal Pemeriksaan:</strong> {{ $checkup->checkup_date }}</p>
            <p><strong>Penanganan:</strong> {{ $checkup->handling }}</p>
            <p><strong>Nama Dokter:</strong> {{ $checkup->doctor->name }}</p>
            <p><strong>Harga Layanan:</strong> Rp{{ number_format($checkup->price, 0, ',', '.') }}</p>
            <p><strong>Hasil Pemeriksaan:</strong> {{ $checkup->checkup_result }}</p>
        </div>

        <div class="footer">
            <p>Generated by Hospital Management System</p>
            <p>&copy; {{ date('Y') }} All Rights Reserved.</p>
        </div>
    </div>
</body>
</html>